# Generated by Django 5.0.4 on 2024-05-22 17:35

from django.db import migrations, models
import datetime


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 5, 21, 0, 0)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listing',
            name='listed_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 5, 21, 0, 0)),
            preserve_default=False,
        ),
    ]
